// <auto-generated />
namespace DatVeMayBay.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class DBFinal : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DBFinal));
        
        string IMigrationMetadata.Id
        {
            get { return "202104230247175_DBFinal"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
